theme: minima
title: Reversing Junk
author: Ben Demick
description: Reversing junk, junk reversing, and opinions about junk.

twitter_username: 3pidemix
github_username: bdemick
linkedin_username: ben-demick

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
