theme: minima
title: Reversing Junk
author: Ben Demick
description: Reversing junk, junk reversing, and opinions about junk.
minima:
  skin: dark
  social_links:
    - { platform: twitter, user_url: "https://twitter.com/3pidemix" }
    - { platform: github, user_url: "https://github.com/bdemick" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/ben-demick"}
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
