theme: minima
title: Reversing Junk
author: Ben Demick
description: Reversing junk, junk reversing, and opinions about junk.
minima:
  skin: dark
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge